autofs: Use different configuration file

diff --git a/meta-openpli/recipes-connectivity/autofs/autofs-4.1.4/autofs.init b/meta-openpli/recipes-connectivity/autofs/autofs-4.1.4/autofs.init
--- a/meta-openpli/recipes-connectivity/autofs/autofs-4.1.4/autofs.init
+++ b/meta-openpli/recipes-connectivity/autofs/autofs-4.1.4/autofs.init
@@ -49,21 +49,10 @@ test -e $DAEMON || exit 0
 # Determine which kind of configuration we're using
 #
 system=debian
-if [ -f /etc/redhat-release ]; then
-	system=redhat
-fi
 
-if [ $system = redhat ]; then
-	. $initdir/functions
-fi
 
-if [ $system = debian ]; then
-	thisscript="$0"
-	if [ ! -f "$thisscript" ]; then
-		echo "$0: Cannot find myself" 1>&2
-		exit 1
-	fi
-fi
+
+
 
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 export PATH
@@ -74,42 +63,22 @@ export PATH
 #
 localoptions=''
 
-#
-# Daemon options
-# e.g. --timeout=60
-#
-daemonoptions=''
+daemonoptions='--ghost '
 
 #
 # load custom settings
 #
-if [ "$system" = "redhat" ]; then
-	LOCALOPTIONS=""
-	DAEMONOPTIONS=""
-	UNDERSCORETODOT=1
-	DISABLE_DIRECT=1
-	DAEMON_EXIT_WAIT=20
+TIMEOUT=5
+DISABLE_DIRECT=1
+DAEMON_EXIT_WAIT=20
 
-	[ -f /etc/sysconfig/autofs ] && . /etc/sysconfig/autofs
+daemonoptions="$daemonoptions --timeout=$TIMEOUT"
 
-	# Over-ride localoptions if set
-	if [ -n "$LOCALOPTIONS" ]; then
-		localoptions=$LOCALOPTIONS
-	fi
 
-	# Over-ride daemonoptions if set
-	if [ -n "$DAEMONOPTIONS" ]; then
-		daemonoptions=$DAEMONOPTIONS
-	fi
-elif [ "$system" = "debian" ]; then
-	TIMEOUT=300
-	DISABLE_DIRECT=1
-	DAEMON_EXIT_WAIT=20
 
-	[ -f /etc/default/autofs ] && . /etc/default/autofs
 
-	daemonoptions="$daemonoptions --timeout=$TIMEOUT"
-fi
+
+
 
 #
 # Check for all maps that are to be loaded
@@ -134,17 +103,7 @@ catnismap()
     else
         map="$1"
     fi
-
-    # Append the map's options at the _start_ if there are any options already
-    # (ie. myopt -> $2,myopt), otherwise just append them at the end.
-    if [ -z "$2" ]; then
-        /usr/bin/ypcat -k "$map" 2> /dev/null | sed -e '/^#/d' -e '/^$/d'
-    else
-        /usr/bin/ypcat -k "$map" 2> /dev/null |
-        sed -e '/^#/d' -e '/^$/d' \
-            -e "s/^[ \t]*\([^ \t]\+\)[ \t]\+\([^ \t]\+\)[ \t]\+-\([^ \t]\+\)/\1 \2 $2,\3/" \
-            -e "s/^[ \t]*\([^ \t]\+\)[ \t]\+\([^ \t]\+\)[ \t]*$/\1 \2 $2/"
-    fi    
+    /usr/bin/ypcat -k "$map" 2> /dev/null | sed -e '/^#/d' -e '/^$/d'
 }
 
 getfilemounts()
@@ -153,14 +112,13 @@ getfilemounts()
         cat /etc/auto.master | awk '{print $0}' | sed -e '/^#/d' -e '/^$/d' | (
         while read auto_master_in
         do
-            if [ "`echo $auto_master_in | grep '^\+'`" = "" ]; then
+            if [ "`echo $auto_master_in | grep '^+'`" = "" ]; then
                 echo $auto_master_in
             else
-                cat /etc/auto.master | grep '^\+' | sed -e '/^#/d' -e '/^$/d' | (
-                    while read map options; do
-                        catnismap `echo "$map" | sed -e 's/^\+//'` $options
-                    done
-                )
+                for nismap in `cat /etc/auto.master | grep '^\+' |
+                        sed -e '/^#/d' -e '/^$/d'`; do
+                    catnismap `echo "$nismap" | sed -e 's/^\+//'`
+                done
             fi
         done
         )
@@ -180,11 +138,7 @@ getnismounts()
 getldapmounts()
 {
     if [ -x /usr/lib/autofs/autofs-ldap-auto-master ]; then
-	[ ! -z $LDAPURI ] && export LDAPURI="$LDAPURI"
-	[ ! -z $LDAPBASE ] && export LDAPBASE="$LDAPBASE"
         /usr/lib/autofs/autofs-ldap-auto-master 2> /dev/null
-	/usr/lib/autofs/autofs-ldap-auto-master -m automountMap \
-	    -e automount -n ou -k cn -v automountInformation 2> /dev/null
     fi
 }
 
@@ -247,13 +201,6 @@ getmounts()
 			-a x`echo $dir | grep -E "^/-"` != 'x' ]
 	    then
 		continue
-	    fi
-
-	    # If possible, canonicalise the path so it will always unmount
-	    # cleanly.
-	    link=`readlink -f "$dir"`
-	    if [ ! -z "$link" ]; then
-		    dir="$link"
 	    fi
 
 	    # Do not include a map if it is a duplicate, maps on top of
@@ -324,7 +271,7 @@ getmounts()
 		maptype=`echo $map | cut -f1 -d:`
 		# Handle degenerate map specifiers
 		if [ "$maptype" = "$map" ] ; then
-		    if [ "$map" = "hesiod" -o "$map" = "userhome" -o "$map" = "ldap" ] ; then
+		    if [ "$map" = "hesiod" -o "$map" = "userhome" ] ; then
 			maptype=$map
 			map=
 		    elif [ "$map" = "multi" ] ; then
@@ -333,7 +280,7 @@ getmounts()
 #		    elif echo "$map" | grep -q '^!'; then
 #		        map=`echo "$map"| sed -e 's/^!//g'`
 		    elif `echo $map | grep -q "^/"` && [ -x "$map" ]; then
-			maptype=program
+			maptype=file
 		    elif [ -x "/etc/$map" ]; then
 			maptype=program
 			map=`echo /etc/$map | sed 's^//^/^g'`
@@ -460,7 +407,7 @@ signal_automounts()
 		done
 	done
 
-	if [ -n "`pidof $DAEMON`" ] ; then
+	if [ -n "`/sbin/pidof $DAEMON`" ] ; then
 		RETVAL=1
 	fi
 
@@ -516,116 +463,24 @@ umount_loopback()
     done
 }
 
-#
-# Redhat start/stop function.
-#
-redhat()
-{
-
-#
-# See how we were called.
-#
-case "$1" in
-  start)
-        # Make sure the autofs filesystem type is available.
-        (grep -q autofs /proc/filesystems || /sbin/modprobe -k autofs4 || /sbin/modprobe -k autofs) 2> /dev/null
-        echo -n $"Starting $prog: "
-        TMP=`mktemp /tmp/autofs.XXXXXX` || { echo $"could not make temp file" >& 2; exit 1; }
-        getmounts | tee $TMP | sh
-        RETVAL=$?
-	if [ -s $TMP ] ; then
-	    if [ $RETVAL -eq 0 ] ; then
-		success "$prog startup"
-	    else
-		failure "$prog startup"
-	    fi
-	    [ $RETVAL = 0 ] && touch /var/lock/subsys/autofs
-	else
-	    echo -n $"No Mountpoints Defined"
-	    success "$prog startup"
-	fi
-	rm -f $TMP
-	echo
-	;;
-  stop)
-	echo -n $"Stopping $prog:"
-	if [ -z "`pidofproc $prog`" -a -z "`getmounts`" ]; then
-		RETVAL=0
-	else
-		umount_loopback
-		signal_automounts
-		RETVAL=$?
-	fi
+stop() {
+	echo -n $"Stopping $prog: "
 	count=0
-	while [ -n "`/sbin/pidof $DAEMON`" -a $count -lt 10 ] ; do
-	   killproc $DAEMON -USR2 >& /dev/null
-	   RETVAL=$?
-	   [ $RETVAL = 0 -a -z "`/sbin/pidof $DAEMON`" ] || sleep 3
-	   count=`expr $count + 1`
+	while [ -n "`pidof $DAEMON`" -a $count -lt 15 ] ; do
+		killall -TERM $prog >& /dev/null
+		RETVAL=$?
+		[ $RETVAL = 0 -a -z "`pidof $DAEMON`" ] || sleep 3
+		count=`expr $count + 1`
 	done
-	umount -a -f -t autofs
-	rm -f /var/lock/subsys/autofs
-	if [ -n "`/sbin/pidof $DAEMON`" ] ; then
-	    failure "$prog shutdown"
+	if [ -n "`pidof $DAEMON`" ] ; then
+		echo "done."
 	else
-	    success "$prog shutdown"
+		echo "failed."
 	fi
-	echo
-	;;
-  restart)
-	redhat stop
-	redhat start
-	;;
-  reload)
-	if [ ! -f /var/lock/subsys/autofs ]; then
-		echo $"$prog not running"
-		RETVAL=1
-		return
-	fi
-	echo $"Checking for changes to /etc/auto.master ...."
-        TMP1=`mktemp /tmp/autofs.XXXXXX` || { echo $"could not make temp file" >& 2; exit 1; }
-        TMP2=`mktemp /tmp/autofs.XXXXXX` || { echo $"could not make temp file" >& 2; exit 1; }
-	getmounts >$TMP1
-	ps axwww|grep "[0-9]:[0-9][0-9] $DAEMON " | (
-	    while read pid tt stat time command; do
-		echo "$command" >>$TMP2
-		if ! grep -q "^$command" $TMP1; then
-		    if ! echo "$command" | grep -q -e --submount; then
-			kill -USR2 $pid 2> /dev/null
-			echo $"Stop $command"
-		    fi
-		else
-			kill -HUP $pid 2> /dev/null
-			echo $"Reload map $command"
-		fi
-	    done
-	)
-	cat $TMP1 | ( while read x; do
-		if ! grep -q "^$x" $TMP2; then
-			$x
-			echo $"Start $x"
-		fi
-        done )
-	rm -f $TMP1 $TMP2
-	;;
-  status)
-	status
-	;;
-  condrestart)
-	[ -f /var/lock/subsys/autofs ] && redhat restart
-        RETVAL=0
-	;;
-  *)
-	echo $"Usage: $0 {start|stop|restart|reload|condrestart|status}"
-	RETVAL=0
-esac
+	return $RETVAL
 }
 
-#
-# Debian start/stop functions.
-#
-debian()
-{
+
 
 case "$1" in
 start)
@@ -692,12 +547,9 @@ stop)
 			  's,.* --pid-file=/var/run/autofs/\([^ ]*\)\.pid.*,\1,; s,_,/,g'`
 			dname=`basename $DAEMON`
 
-			start-stop-daemon --stop --quiet \
-					--retry USR2/$DAEMON_EXIT_WAIT \
-					--pidfile $file --name $dname
+			start-stop-daemon --stop --quiet --pidfile $file --name $dname
 
 			ret=$?
-
 			case $ret in
 			0)
 #				echo -n " $mnt"
@@ -723,8 +575,8 @@ stop)
 reload)
 	echo "Reloading automounter: checking for changes ... "
 
-	TMP1=`mktemp -t autofs.XXXXXX`
-	TMP2=`mktemp -t autofs.XXXXXX`
+	TMP1=`mktemp autofs.XXXXXX`
+	TMP2=`mktemp autofs.XXXXXX`
 
 	getmounts >$TMP1
 
@@ -774,8 +626,8 @@ reload)
 	rm -f $TMP1 $TMP2
 	;;
 force-reload|restart)
-	debian stop
-	debian start
+	stop
+	start
 	;;
 status)
 	status
@@ -791,13 +643,9 @@ active)
 	exit 1
 	;;
 esac
-}
 
-RETVAL=0
-if [ $system = debian ]; then
-	debian "$@"
-elif [ $system = redhat ]; then
-	redhat "$@"
-fi
+exit 0
 
-exit $RETVAL
+
+
+
